services:
  - type: web
    name: stock-management-app
    env: python
    buildCommand: |
      cd client
      npm install
      npm run build
    startCommand: python backend/server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
