services:
  - type: web
    name: stock-app
    env: python
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "python backend/server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
